snowflakedbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: SYSADMIN
      warehouse: JYM_TASTY_BYTES_DBT_WH
      database: JYM_TASTY_BYTES_DBT_DB
      schema: PUBLIC
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: tasty_bytes_dbt_db
      schema: prod
      warehouse: tasty_bytes_dbt_wh